// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using receptionHubBackend.Data;

#nullable disable

namespace receptionHubBackend.Migrations
{
    [DbContext(typeof(ReceptionHubDbContext))]
    partial class ReceptionHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("receptionHubBackend.Models.ArhiviranaRezervacija", b =>
                {
                    b.Property<int>("IdArhive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArhive"));

                    b.Property<int>("ArhiviraoRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<int>("BrojDjece")
                        .HasColumnType("integer");

                    b.Property<int>("BrojNocenja")
                        .HasColumnType("integer");

                    b.Property<int>("BrojOdraslih")
                        .HasColumnType("integer");

                    b.Property<string>("BrojRezervacije")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrojSobe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CijenaPoNoci")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DatumArhiviranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EksterniBrojRezervacije")
                        .HasColumnType("text");

                    b.Property<int>("NacinRezervacije")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<int>("OriginalnaRezervacijaId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalniGostId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalniRazlogOtkazivanja")
                        .HasColumnType("text");

                    b.Property<int>("OriginalniRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OriginalnoVrijemeKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OriginalnoVrijemeOtkazivanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Popust")
                        .HasColumnType("numeric");

                    b.Property<int>("RazlogArhiviranja")
                        .HasColumnType("integer");

                    b.Property<int>("SobaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("numeric");

                    b.Property<int>("UkupnoGostiju")
                        .HasColumnType("integer");

                    b.Property<string>("Zahtjevi")
                        .HasColumnType("text");

                    b.HasKey("IdArhive");

                    b.HasIndex("DatumArhiviranja")
                        .HasDatabaseName("IX_ArhiviranaRezervacija_DatumArhiviranja");

                    b.HasIndex("OriginalnaRezervacijaId")
                        .HasDatabaseName("IX_ArhiviranaRezervacija_OriginalniId");

                    b.HasIndex("OriginalniGostId")
                        .HasDatabaseName("IX_ArhiviranaRezervacija_OriginalniGostId");

                    b.ToTable("ArhiviraneRezervacije");
                });

            modelBuilder.Entity("receptionHubBackend.Models.ArhiviraniGost", b =>
                {
                    b.Property<int>("IdArhive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArhive"));

                    b.Property<int?>("ArhiviranaRezervacijaId")
                        .HasColumnType("integer");

                    b.Property<int>("ArhiviraoRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumArhiviranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dodatno")
                        .HasColumnType("text");

                    b.Property<string>("Drzava")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .HasColumnType("text");

                    b.Property<string>("KontaktOsoba")
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NazivFirme")
                        .HasColumnType("text");

                    b.Property<int>("OriginalniGostId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginalniRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OriginalnoVrijemeAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OriginalnoVrijemeKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prezime")
                        .HasColumnType("text");

                    b.Property<int>("RazlogArhiviranja")
                        .HasColumnType("integer");

                    b.Property<string>("SlikaDokumenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipGosta")
                        .HasColumnType("integer");

                    b.Property<bool>("VIPGost")
                        .HasColumnType("boolean");

                    b.HasKey("IdArhive");

                    b.HasIndex("ArhiviranaRezervacijaId");

                    b.HasIndex("DatumArhiviranja")
                        .HasDatabaseName("IX_ArhiviraniGost_DatumArhiviranja");

                    b.HasIndex("OriginalniGostId")
                        .HasDatabaseName("IX_ArhiviraniGost_OriginalniId");

                    b.ToTable("ArhiviraniGosti");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Gost", b =>
                {
                    b.Property<int>("IdGosta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGosta"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("text");

                    b.Property<string>("Dodatno")
                        .HasColumnType("text");

                    b.Property<string>("Drzava")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KontaktOsoba")
                        .HasColumnType("text");

                    b.Property<string>("NazivFirme")
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RecepcionerId")
                        .HasColumnType("integer");

                    b.Property<string>("SlikaDokumenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipDokumenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipGosta")
                        .HasColumnType("integer");

                    b.Property<bool>("VIPGost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("VrijemeAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VrijemeKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdGosta");

                    b.HasIndex("BrojTelefona")
                        .HasDatabaseName("IX_Gost_BrojTelefona");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Gost_Email");

                    b.ToTable("Gosti");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalji")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DodatniPodaci")
                        .HasColumnType("text");

                    b.Property<int?>("GostId")
                        .HasColumnType("integer");

                    b.Property<string>("HttpMetoda")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IPAdresa")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Izvor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Poruka")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Putanja")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RecepcionerId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int?>("StatusKod")
                        .HasColumnType("integer");

                    b.Property<string>("TijeloZahtjeva")
                        .HasColumnType("text");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<string>("TipIzuzetka")
                        .HasColumnType("text");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("TrajanjeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zaglavlja")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tip");

                    b.HasIndex("Vrijeme");

                    b.ToTable("Logovi");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Recepcioner", b =>
                {
                    b.Property<int>("IdRecepcionera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecepcionera"));

                    b.Property<bool>("Aktivan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumKreiranjaRacuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PosljednjiLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Pozicija")
                        .HasColumnType("integer");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SlikaProfila")
                        .HasColumnType("text");

                    b.HasKey("IdRecepcionera");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Recepcioner_Email");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique()
                        .HasDatabaseName("IX_Recepcioner_KorisnickoIme");

                    b.ToTable("Recepcioneri");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Rezervacija", b =>
                {
                    b.Property<int>("IdRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRezervacije"));

                    b.Property<int>("BrojDjece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BrojOdraslih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("BrojRezervacije")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("CijenaPoNoci")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EksterniBrojRezervacije")
                        .HasColumnType("text");

                    b.Property<int>("NacinRezervacije")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Popust")
                        .HasColumnType("numeric");

                    b.Property<string>("RazlogOtkazivanja")
                        .HasColumnType("text");

                    b.Property<int>("RecepcionerId")
                        .HasColumnType("integer");

                    b.Property<int>("SobaId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UkupnaCijena")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("VrijemeAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VrijemeKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("VrijemeOtkazivanja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zahtjevi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdRezervacije");

                    b.HasIndex("BrojRezervacije")
                        .IsUnique()
                        .HasDatabaseName("IX_Rezervacija_BrojRezervacije");

                    b.HasIndex("RecepcionerId");

                    b.HasIndex("SobaId")
                        .HasDatabaseName("IX_Rezervacija_SobaId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Rezervacija_Status");

                    b.HasIndex("DatumDolaska", "DatumOdlaska")
                        .HasDatabaseName("IX_Rezervacija_Datumi");

                    b.ToTable("Rezervacije", t =>
                        {
                            t.HasCheckConstraint("CK_Rezervacija_Datumi", "\"DatumOdlaska\" > \"DatumDolaska\"");

                            t.HasCheckConstraint("CK_Rezervacija_Gosti", "\"BrojOdraslih\" + \"BrojDjece\" > 0");
                        });
                });

            modelBuilder.Entity("receptionHubBackend.Models.RezervacijaGost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GostId")
                        .HasColumnType("integer");

                    b.Property<bool>("JeGlavniGost")
                        .HasColumnType("boolean");

                    b.Property<string>("PosebneNapomene")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GostId");

                    b.HasIndex("RezervacijaId", "GostId")
                        .IsUnique();

                    b.ToTable("RezervacijaGosti");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Soba", b =>
                {
                    b.Property<int>("IdSobe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSobe"));

                    b.Property<int?>("AzuriraoRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<int?>("BrojBracnihKreveta")
                        .HasColumnType("integer");

                    b.Property<int>("BrojKreveta")
                        .HasColumnType("integer");

                    b.Property<int?>("BrojOdvojenihKreveta")
                        .HasColumnType("integer");

                    b.Property<string>("BrojSobe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("CijenaPoNociBAM")
                        .HasColumnType("numeric");

                    b.Property<string>("GlavnaSlika")
                        .HasColumnType("text");

                    b.Property<bool>("ImaDodatniKrevet")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaFen")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaKlimu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImaKupatilo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaMiniBar")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaPeglu")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaPogledNaGrad")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaRadniSto")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaTus")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImaTv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ImaWiFi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("KratkiOpis")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("KreiraoRecepcionerId")
                        .HasColumnType("integer");

                    b.Property<int>("MaksimalnoGostiju")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PlaniranoOslobadjanje")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TipSobe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VrijemeAzuriranja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VrijemeKreiranja")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdSobe");

                    b.HasIndex("BrojSobe")
                        .IsUnique()
                        .HasDatabaseName("IX_Soba_BrojSobe");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Soba_Status");

                    b.ToTable("Sobe", t =>
                        {
                            t.HasCheckConstraint("CK_Soba_Cijena", "\"CijenaPoNociBAM\" >= 0");
                        });
                });

            modelBuilder.Entity("receptionHubBackend.Models.ArhiviraniGost", b =>
                {
                    b.HasOne("receptionHubBackend.Models.ArhiviranaRezervacija", null)
                        .WithMany()
                        .HasForeignKey("ArhiviranaRezervacijaId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("receptionHubBackend.Models.Rezervacija", b =>
                {
                    b.HasOne("receptionHubBackend.Models.Recepcioner", "Recepcioner")
                        .WithMany()
                        .HasForeignKey("RecepcionerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("receptionHubBackend.Models.Soba", "Soba")
                        .WithMany()
                        .HasForeignKey("SobaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recepcioner");

                    b.Navigation("Soba");
                });

            modelBuilder.Entity("receptionHubBackend.Models.RezervacijaGost", b =>
                {
                    b.HasOne("receptionHubBackend.Models.Gost", "Gost")
                        .WithMany("RezervacijeGosta")
                        .HasForeignKey("GostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("receptionHubBackend.Models.Rezervacija", "Rezervacija")
                        .WithMany("GostiURezervaciji")
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gost");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Gost", b =>
                {
                    b.Navigation("RezervacijeGosta");
                });

            modelBuilder.Entity("receptionHubBackend.Models.Rezervacija", b =>
                {
                    b.Navigation("GostiURezervaciji");
                });
#pragma warning restore 612, 618
        }
    }
}
